#pragma once

#ifdef PC
#   define _SCREEN_SIZE_MULTIPLIER 1
#else
#   define _SCREEN_SIZE_MULTIPLIER 1
#endif

#define SCREEN_X 320*_SCREEN_SIZE_MULTIPLIER
#define SCREEN_Y 528*_SCREEN_SIZE_MULTIPLIER


#ifdef PC
#   define UNIVERSIAL_FILE_READ O_RDONLY
#else
#   define UNIVERSIAL_FILE_READ OPEN_READ
#endif